using Microsoft.EntityFrameworkCore;
using NavSnap.Models.Entities;

namespace NavSnap.Data
{
    public static class DbSeeder
    {
        public static async Task SeedAsync(AppDbContext db)
        {
            await db.Database.EnsureCreatedAsync();

            async Task ExecRequiredAsync(string sql)
            {
                await db.Database.ExecuteSqlRawAsync(sql);
            }

            async Task ExecSafeAsync(string sql)
            {
                try
                {
                    await db.Database.ExecuteSqlRawAsync(sql);
                }
                catch (Exception ex)
                {
                    // Keep app startup alive on lock/timeout during schema hardening.
                    Console.WriteLine($"[DbSeeder][WARN] SQL skipped: {ex.Message}");
                }
            }

            // Core tables / columns.
            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_m_user (
                    nrp varchar(30) PRIMARY KEY,
                    ""user"" varchar(50) NOT NULL UNIQUE,
                    password varchar(100) NOT NULL,
                    terakhir_login timestamp NULL,
                    status boolean NOT NULL DEFAULT true,
                    path_foto_profile varchar(255) NULL,
                    employee_nrp varchar(30) NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_m_employee_profiles (
                    nrp varchar(30) PRIMARY KEY,
                    full_name varchar(150) NOT NULL,
                    full_address varchar(500) NULL,
                    job_title varchar(100) NULL,
                    position varchar(100) NULL,
                    division varchar(100) NULL,
                    department varchar(100) NULL,
                    phone varchar(30) NULL,
                    email varchar(120) NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    created_at timestamp NOT NULL DEFAULT now(),
                    updated_at timestamp NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_store_submissions (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sales_user_id integer NOT NULL,
                    store_name varchar(150) NOT NULL,
                    address varchar(300) NULL,
                    latitude double precision NOT NULL,
                    longitude double precision NOT NULL,
                    radius_meters integer NOT NULL DEFAULT 100,
                    submission_note varchar(500) NULL,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    admin_note varchar(500) NULL,
                    proposed_visit_date date NULL,
                    approved_checkpoint_id integer NULL,
                    approved_by integer NULL,
                    approved_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now(),
                    updated_at timestamp NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_sales_daily_targets (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    target_date date NOT NULL,
                    target_stores integer NOT NULL DEFAULT 0,
                    notes varchar(200) NULL,
                    created_by integer NULL,
                    created_at timestamp NOT NULL DEFAULT now(),
                    updated_at timestamp NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_m_attendance_settings (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    location_name varchar(150) NOT NULL,
                    latitude double precision NOT NULL,
                    longitude double precision NOT NULL,
                    radius_meters integer NOT NULL DEFAULT 100,
                    is_active boolean NOT NULL DEFAULT true,
                    created_by integer NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_attendance_logs (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    attendance_date date NOT NULL,
                    check_in_at timestamp NULL,
                    check_out_at timestamp NULL,
                    check_in_latitude double precision NULL,
                    check_in_longitude double precision NULL,
                    check_out_latitude double precision NULL,
                    check_out_longitude double precision NULL,
                    status varchar(20) NOT NULL DEFAULT 'present',
                    notes varchar(300) NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_leave_requests (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    request_date date NOT NULL,
                    leave_date_from date NOT NULL,
                    leave_date_to date NOT NULL,
                    leave_type varchar(30) NOT NULL,
                    reason varchar(500) NULL,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    approved_by integer NULL,
                    approved_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_overtime_requests (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    request_date date NOT NULL,
                    overtime_date date NOT NULL,
                    hours numeric(8,2) NOT NULL,
                    reason varchar(500) NULL,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    approved_by integer NULL,
                    approved_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS is_mandatory boolean NOT NULL DEFAULT false;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS source_submission_id integer NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS visit_photo_path varchar(255) NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS point_earned integer NOT NULL DEFAULT 0;
            ");

            // Indexes.
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_store_submissions_sales_status ON tbl_t_store_submissions (sales_user_id, status);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_store_submissions_checkpoint ON tbl_t_store_submissions (approved_checkpoint_id);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_sales_visits_source_submission ON tbl_t_sales_visits (source_submission_id);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_m_user_employee_nrp ON tbl_m_user (employee_nrp);");
            await ExecSafeAsync(@"CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_daily_targets_user_date ON tbl_t_sales_daily_targets (user_id, target_date);");
            await ExecSafeAsync(@"CREATE UNIQUE INDEX IF NOT EXISTS ux_attendance_logs_user_date ON tbl_t_attendance_logs (user_id, attendance_date);");

            // Foreign keys. Use NOT VALID to avoid long validation locks at startup.
            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_m_user_employee_nrp') THEN
                        ALTER TABLE tbl_m_user
                        ADD CONSTRAINT fk_m_user_employee_nrp
                        FOREIGN KEY (employee_nrp) REFERENCES tbl_m_employee_profiles (nrp)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_logs_user') THEN
                        ALTER TABLE tbl_t_attendance_logs
                        ADD CONSTRAINT fk_attendance_logs_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_leave_requests_user') THEN
                        ALTER TABLE tbl_t_leave_requests
                        ADD CONSTRAINT fk_leave_requests_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_leave_requests_approved_by') THEN
                        ALTER TABLE tbl_t_leave_requests
                        ADD CONSTRAINT fk_leave_requests_approved_by
                        FOREIGN KEY (approved_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_overtime_requests_user') THEN
                        ALTER TABLE tbl_t_overtime_requests
                        ADD CONSTRAINT fk_overtime_requests_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_overtime_requests_approved_by') THEN
                        ALTER TABLE tbl_t_overtime_requests
                        ADD CONSTRAINT fk_overtime_requests_approved_by
                        FOREIGN KEY (approved_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sales_daily_targets_user') THEN
                        ALTER TABLE tbl_t_sales_daily_targets
                        ADD CONSTRAINT fk_sales_daily_targets_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sales_daily_targets_created_by') THEN
                        ALTER TABLE tbl_t_sales_daily_targets
                        ADD CONSTRAINT fk_sales_daily_targets_created_by
                        FOREIGN KEY (created_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_store_submissions_sales_user') THEN
                        ALTER TABLE tbl_t_store_submissions
                        ADD CONSTRAINT fk_store_submissions_sales_user
                        FOREIGN KEY (sales_user_id) REFERENCES tbl_m_users (id)
                        ON DELETE RESTRICT
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_store_submissions_checkpoint') THEN
                        ALTER TABLE tbl_t_store_submissions
                        ADD CONSTRAINT fk_store_submissions_checkpoint
                        FOREIGN KEY (approved_checkpoint_id) REFERENCES tbl_m_checkpoints (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_store_submissions_approved_by') THEN
                        ALTER TABLE tbl_t_store_submissions
                        ADD CONSTRAINT fk_store_submissions_approved_by
                        FOREIGN KEY (approved_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sales_visits_source_submission') THEN
                        ALTER TABLE tbl_t_sales_visits
                        ADD CONSTRAINT fk_sales_visits_source_submission
                        FOREIGN KEY (source_submission_id) REFERENCES tbl_t_store_submissions (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            // --- Roles ---
            if (!await db.Roles.AnyAsync())
            {
                var roles = new List<Role>
                {
                    new() { RoleName = "Administrator", Description = "Full akses sistem", IsActive = true },
                    new() { RoleName = "Sales",         Description = "Sales representative",  IsActive = true },
                    new() { RoleName = "Pengawas",      Description = "Supervisor / pengawas sales", IsActive = true }
                };
                await db.Roles.AddRangeAsync(roles);
                await db.SaveChangesAsync();
            }

            // --- Menus ---
            if (!await db.Menus.AnyAsync())
            {
                var menus = new List<Menu>
                {
                    new() { MenuName = "Dashboard",         MenuUrl = "/Home/Index",                   IconClass = "fas fa-tachometer-alt", SortOrder = 1,  ParentId = null },
                    new() { MenuName = "Tracking Sales",    MenuUrl = "#",                             IconClass = "fas fa-map-marked-alt", SortOrder = 2,  ParentId = null },
                    new() { MenuName = "Live Tracking",     MenuUrl = "/SalesTracking/Index",          IconClass = "fas fa-satellite-dish", SortOrder = 3,  ParentId = null },
                    new() { MenuName = "Riwayat Kunjungan", MenuUrl = "/SalesTracking/History",        IconClass = "fas fa-history",        SortOrder = 4,  ParentId = null },
                    new() { MenuName = "Checkpoint",        MenuUrl = "#",                             IconClass = "fas fa-map-pin",        SortOrder = 5,  ParentId = null },
                    new() { MenuName = "Daftar Checkpoint", MenuUrl = "/Checkpoint/Index",             IconClass = "fas fa-list",           SortOrder = 6,  ParentId = null },
                    new() { MenuName = "Peta Checkpoint",   MenuUrl = "/Checkpoint/Map",               IconClass = "fas fa-map",            SortOrder = 7,  ParentId = null },
                    new() { MenuName = "Administrasi",      MenuUrl = "#",                             IconClass = "fas fa-cogs",           SortOrder = 8,  ParentId = null },
                    new() { MenuName = "Manajemen User",    MenuUrl = "/User/Index",                   IconClass = "fas fa-users",          SortOrder = 9,  ParentId = null },
                    new() { MenuName = "Manajemen Role",    MenuUrl = "/Role/Index",                   IconClass = "fas fa-user-shield",    SortOrder = 10, ParentId = null },
                    new() { MenuName = "Manajemen Menu",    MenuUrl = "/MenuAdmin/Index",              IconClass = "fas fa-bars",           SortOrder = 11, ParentId = null },
                    new() { MenuName = "Akses Role-Menu",   MenuUrl = "/Role/AccessMenu",              IconClass = "fas fa-key",            SortOrder = 12, ParentId = null },
                };
                await db.Menus.AddRangeAsync(menus);
                await db.SaveChangesAsync();
            }

            // Ensure mobile user menu exists.
            var mobileMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "/MUser/Index");
            if (mobileMenu == null)
            {
                var nextSort = (await db.Menus.MaxAsync(m => (int?)m.SortOrder) ?? 0) + 1;
                mobileMenu = new Menu
                {
                    MenuName = "User Mobile",
                    MenuUrl = "/MUser/Index",
                    IconClass = "fas fa-mobile-alt",
                    SortOrder = nextSort,
                    ParentId = null,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(mobileMenu);
                await db.SaveChangesAsync();
            }

            // Ensure daily target menu exists.
            var dailyTargetMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "/SalesTarget/Index");
            if (dailyTargetMenu == null)
            {
                var nextSort = (await db.Menus.MaxAsync(m => (int?)m.SortOrder) ?? 0) + 1;
                dailyTargetMenu = new Menu
                {
                    MenuName = "Target Harian Sales",
                    MenuUrl = "/SalesTarget/Index",
                    IconClass = "fas fa-bullseye",
                    SortOrder = nextSort,
                    ParentId = null,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(dailyTargetMenu);
                await db.SaveChangesAsync();
            }

            var payrollMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "#" && m.MenuName == "Payroll");
            if (payrollMenu == null)
            {
                var nextSort = (await db.Menus.MaxAsync(m => (int?)m.SortOrder) ?? 0) + 1;
                payrollMenu = new Menu
                {
                    MenuName = "Payroll",
                    MenuUrl = "#",
                    IconClass = "fas fa-money-check-alt",
                    SortOrder = nextSort,
                    ParentId = null,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(payrollMenu);
                await db.SaveChangesAsync();
            }

            async Task EnsurePayrollChild(string name, string url, string icon, int order)
            {
                var exists = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == url);
                if (exists != null) return;
                await db.Menus.AddAsync(new Menu
                {
                    MenuName = name,
                    MenuUrl = url,
                    IconClass = icon,
                    SortOrder = order,
                    ParentId = payrollMenu!.Id,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                });
                await db.SaveChangesAsync();
            }

            await EnsurePayrollChild("Setting Lokasi Absen", "/Payroll/AttendanceSettings", "fas fa-map-marked-alt", payrollMenu.SortOrder + 1);
            await EnsurePayrollChild("Laporan Absen", "/Payroll/AttendanceReport", "fas fa-file-alt", payrollMenu.SortOrder + 2);
            await EnsurePayrollChild("Izin & Lembur", "/Payroll/LeaveOvertime", "fas fa-user-clock", payrollMenu.SortOrder + 3);

            // --- Admin user ---
            if (!await db.Users.AnyAsync())
            {
                var admin = new User
                {
                    Username = "admin",
                    Password = "admin",
                    FullName = "Administrator",
                    Email = "admin@navsnap.com",
                    IsActive = true
                };
                await db.Users.AddAsync(admin);
                await db.SaveChangesAsync();

                var adminRole = await db.Roles.FirstAsync(r => r.RoleName == "Administrator");
                await db.UserRoles.AddAsync(new UserRole { UserId = admin.Id, RoleId = adminRole.Id });
                await db.SaveChangesAsync();

                // Assign all menus to Administrator
                var allMenuIds = await db.Menus.Select(m => m.Id).ToListAsync();
                var roleMenus = allMenuIds.Select(mid => new RoleMenu { RoleId = adminRole.Id, MenuId = mid });
                await db.RoleMenus.AddRangeAsync(roleMenus);
                await db.SaveChangesAsync();

                // Sales role: dashboard + tracking + checkpoint view
                var salesRole = await db.Roles.FirstAsync(r => r.RoleName == "Sales");
                var salesMenuIds = await db.Menus
                    .Where(m => m.MenuUrl == "/Home/Index" ||
                                m.MenuUrl == "/SalesTracking/Index" ||
                                m.MenuUrl == "/Checkpoint/Index")
                    .Select(m => m.Id).ToListAsync();
                await db.RoleMenus.AddRangeAsync(salesMenuIds.Select(mid => new RoleMenu { RoleId = salesRole.Id, MenuId = mid }));

                // Pengawas role: dashboard + tracking + checkpoint
                var pengawasRole = await db.Roles.FirstAsync(r => r.RoleName == "Pengawas");
                var pengawasMenuIds = await db.Menus
                    .Where(m => m.MenuUrl == "/Home/Index" ||
                                m.MenuUrl == "/SalesTracking/Index" ||
                                m.MenuUrl == "/SalesTracking/History" ||
                                m.MenuUrl == "/Checkpoint/Index" ||
                                m.MenuUrl == "/Checkpoint/Map")
                    .Select(m => m.Id).ToListAsync();
                await db.RoleMenus.AddRangeAsync(pengawasMenuIds.Select(mid => new RoleMenu { RoleId = pengawasRole.Id, MenuId = mid }));

                await db.SaveChangesAsync();
            }

            // Ensure Administrator has access to mobile user menu.
            var adminRoleExisting = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Administrator");
            if (adminRoleExisting != null && mobileMenu != null)
            {
                var hasAccess = await db.RoleMenus.AnyAsync(rm => rm.RoleId == adminRoleExisting.Id && rm.MenuId == mobileMenu.Id);
                if (!hasAccess)
                {
                    await db.RoleMenus.AddAsync(new RoleMenu
                    {
                        RoleId = adminRoleExisting.Id,
                        MenuId = mobileMenu.Id
                    });
                    await db.SaveChangesAsync();
                }
            }

            // Ensure Administrator and Pengawas can access daily target settings.
            if (dailyTargetMenu != null)
            {
                var adminRole = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Administrator");
                if (adminRole != null)
                {
                    var adminHas = await db.RoleMenus.AnyAsync(rm => rm.RoleId == adminRole.Id && rm.MenuId == dailyTargetMenu.Id);
                    if (!adminHas)
                    {
                        await db.RoleMenus.AddAsync(new RoleMenu { RoleId = adminRole.Id, MenuId = dailyTargetMenu.Id });
                        await db.SaveChangesAsync();
                    }
                }

                var pengawasRole = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Pengawas");
                if (pengawasRole != null)
                {
                    var pengawasHas = await db.RoleMenus.AnyAsync(rm => rm.RoleId == pengawasRole.Id && rm.MenuId == dailyTargetMenu.Id);
                    if (!pengawasHas)
                    {
                        await db.RoleMenus.AddAsync(new RoleMenu { RoleId = pengawasRole.Id, MenuId = dailyTargetMenu.Id });
                        await db.SaveChangesAsync();
                    }
                }
            }

            // Ensure payroll menus access by role.
            if (payrollMenu != null)
            {
                var payrollMenuIds = await db.Menus
                    .Where(m => m.Id == payrollMenu.Id || m.ParentId == payrollMenu.Id)
                    .Select(m => m.Id)
                    .ToListAsync();

                async Task EnsureRoleMenus(string roleName)
                {
                    var role = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == roleName);
                    if (role == null) return;
                    foreach (var mid in payrollMenuIds)
                    {
                        var has = await db.RoleMenus.AnyAsync(rm => rm.RoleId == role.Id && rm.MenuId == mid);
                        if (!has)
                            await db.RoleMenus.AddAsync(new RoleMenu { RoleId = role.Id, MenuId = mid });
                    }
                    await db.SaveChangesAsync();
                }

                await EnsureRoleMenus("Administrator");
                await EnsureRoleMenus("Pengawas");
                await EnsureRoleMenus("Sales");
            }
        }
    }
}
