using Microsoft.EntityFrameworkCore;
using NavSnap.Models.Entities;

namespace NavSnap.Data
{
    public static class DbSeeder
    {
        // ── Bump this string whenever DDL schema changes ──────────────────────
        private const string SchemaVersion = "v14";

        public static async Task SeedAsync(AppDbContext db)
        {
            await db.Database.EnsureCreatedAsync();

            async Task ExecRequiredAsync(string sql)
            {
                await db.Database.ExecuteSqlRawAsync(sql);
            }

            async Task ExecSafeAsync(string sql)
            {
                try
                {
                    await db.Database.ExecuteSqlRawAsync(sql);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[DbSeeder][WARN] SQL skipped: {ex.Message}");
                }
            }

            // ── Schema version guard ──────────────────────────────────────────
            // Only runs CREATE TABLE / ALTER TABLE / CREATE INDEX / FK DDL once.
            // After that, only lightweight data-seed checks run on startup.
            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_schema_version (
                    version   varchar(20) PRIMARY KEY,
                    applied_at timestamp  NOT NULL DEFAULT now()
                );
            ");

            bool schemaMigrationNeeded = !(await db.Database
                .SqlQueryRaw<string>("SELECT version FROM tbl_schema_version WHERE version = {0}", SchemaVersion)
                .AnyAsync());

            if (schemaMigrationNeeded)
            {
                Console.WriteLine($"[DbSeeder] Applying schema migration {SchemaVersion}...");


            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_m_user (
                    nrp varchar(30) PRIMARY KEY,
                    ""user"" varchar(50) NOT NULL UNIQUE,
                    password varchar(100) NOT NULL,
                    terakhir_login timestamp NULL,
                    status boolean NOT NULL DEFAULT true,
                    path_foto_profile varchar(255) NULL,
                    employee_nrp varchar(30) NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_m_employee_profiles (
                    nrp varchar(30) PRIMARY KEY,
                    full_name varchar(150) NOT NULL,
                    full_address varchar(500) NULL,
                    job_title varchar(100) NULL,
                    position varchar(100) NULL,
                    division varchar(100) NULL,
                    department varchar(100) NULL,
                    phone varchar(30) NULL,
                    email varchar(120) NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    created_at timestamp NOT NULL DEFAULT now(),
                    updated_at timestamp NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_store_submissions (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sales_user_id integer NOT NULL,
                    store_name varchar(150) NOT NULL,
                    address varchar(300) NULL,
                    latitude double precision NOT NULL,
                    longitude double precision NOT NULL,
                    radius_meters integer NOT NULL DEFAULT 100,
                    submission_note varchar(500) NULL,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    admin_note varchar(500) NULL,
                    proposed_visit_date date NULL,
                    approved_checkpoint_id integer NULL,
                    approved_by integer NULL,
                    approved_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now(),
                    updated_at timestamp NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_sales_daily_targets (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    target_date date NOT NULL,
                    target_stores integer NOT NULL DEFAULT 0,
                    notes varchar(200) NULL,
                    created_by integer NULL,
                    created_at timestamp NOT NULL DEFAULT now(),
                    updated_at timestamp NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_m_attendance_settings (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    location_name varchar(150) NOT NULL,
                    latitude double precision NOT NULL,
                    longitude double precision NOT NULL,
                    radius_meters integer NOT NULL DEFAULT 100,
                    is_active boolean NOT NULL DEFAULT true,
                    created_by integer NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_m_attendance_geofence_points (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    attendance_setting_id integer NOT NULL,
                    seq_no integer NOT NULL,
                    latitude double precision NOT NULL,
                    longitude double precision NOT NULL
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_attendance_logs (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    attendance_date date NOT NULL,
                    check_in_at timestamp NULL,
                    check_out_at timestamp NULL,
                    check_in_latitude double precision NULL,
                    check_in_longitude double precision NULL,
                    check_out_latitude double precision NULL,
                    check_out_longitude double precision NULL,
                    status varchar(20) NOT NULL DEFAULT 'present',
                    notes varchar(300) NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_leave_requests (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    request_date date NOT NULL,
                    leave_date_from date NOT NULL,
                    leave_date_to date NOT NULL,
                    leave_type varchar(30) NOT NULL,
                    reason varchar(500) NULL,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    approved_by integer NULL,
                    approved_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_overtime_requests (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    request_date date NOT NULL,
                    overtime_date date NOT NULL,
                    hours numeric(8,2) NOT NULL,
                    reason varchar(500) NULL,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    approved_by integer NULL,
                    approved_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_leave_requests
                ADD COLUMN IF NOT EXISTS approval_stage integer NOT NULL DEFAULT 1;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_leave_requests
                ADD COLUMN IF NOT EXISTS supervisor_approved_by integer NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_leave_requests
                ADD COLUMN IF NOT EXISTS supervisor_approved_at timestamp NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_leave_requests
                ADD COLUMN IF NOT EXISTS hr_approved_by integer NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_leave_requests
                ADD COLUMN IF NOT EXISTS hr_approved_at timestamp NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_leave_requests
                ADD COLUMN IF NOT EXISTS sla_due_at timestamp NULL;
            ");

            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_overtime_requests
                ADD COLUMN IF NOT EXISTS approval_stage integer NOT NULL DEFAULT 1;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_overtime_requests
                ADD COLUMN IF NOT EXISTS supervisor_approved_by integer NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_overtime_requests
                ADD COLUMN IF NOT EXISTS supervisor_approved_at timestamp NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_overtime_requests
                ADD COLUMN IF NOT EXISTS hr_approved_by integer NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_overtime_requests
                ADD COLUMN IF NOT EXISTS hr_approved_at timestamp NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_overtime_requests
                ADD COLUMN IF NOT EXISTS sla_due_at timestamp NULL;
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_sales_visit_schedules (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    checkpoint_id integer NOT NULL,
                    schedule_date date NOT NULL,
                    start_time varchar(5) NOT NULL,
                    end_time varchar(5) NOT NULL,
                    status varchar(20) NOT NULL DEFAULT 'planned',
                    source_submission_id integer NULL,
                    created_by integer NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_audit_logs (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NULL,
                    module varchar(50) NOT NULL,
                    action varchar(80) NOT NULL,
                    entity_name varchar(80) NULL,
                    entity_id integer NULL,
                    description varchar(500) NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS is_mandatory boolean NOT NULL DEFAULT false;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS source_submission_id integer NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS visit_photo_path varchar(255) NULL;
            ");
            await ExecRequiredAsync(@"
                ALTER TABLE tbl_t_sales_visits
                ADD COLUMN IF NOT EXISTS point_earned integer NOT NULL DEFAULT 0;
            ");

            // Indexes.
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_store_submissions_sales_status ON tbl_t_store_submissions (sales_user_id, status);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_store_submissions_checkpoint ON tbl_t_store_submissions (approved_checkpoint_id);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_sales_visits_source_submission ON tbl_t_sales_visits (source_submission_id);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_m_user_employee_nrp ON tbl_m_user (employee_nrp);");
            await ExecSafeAsync(@"CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_daily_targets_user_date ON tbl_t_sales_daily_targets (user_id, target_date);");
            await ExecSafeAsync(@"CREATE UNIQUE INDEX IF NOT EXISTS ux_attendance_logs_user_date ON tbl_t_attendance_logs (user_id, attendance_date);");
            await ExecSafeAsync(@"CREATE UNIQUE INDEX IF NOT EXISTS ux_attendance_geofence_setting_seq ON tbl_m_attendance_geofence_points (attendance_setting_id, seq_no);");
            await ExecSafeAsync(@"CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_visit_schedules_slot ON tbl_t_sales_visit_schedules (user_id, checkpoint_id, schedule_date, start_time, end_time);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_audit_logs_module_created ON tbl_t_audit_logs (module, created_at);");

            await ExecSafeAsync(@"ALTER TABLE tbl_m_users ADD COLUMN IF NOT EXISTS profile_photo_path varchar(255) NULL;");
            await ExecSafeAsync(@"ALTER TABLE tbl_m_users ADD COLUMN IF NOT EXISTS theme_preference varchar(30) NOT NULL DEFAULT 'ocean';");
            await ExecSafeAsync(@"ALTER TABLE tbl_m_users ADD COLUMN IF NOT EXISTS session_version integer NOT NULL DEFAULT 1;");
            await ExecSafeAsync(@"ALTER TABLE tbl_m_users ADD COLUMN IF NOT EXISTS last_login_at timestamp NULL;");

            // Foreign keys. Use NOT VALID to avoid long validation locks at startup.
            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_m_user_employee_nrp') THEN
                        ALTER TABLE tbl_m_user
                        ADD CONSTRAINT fk_m_user_employee_nrp
                        FOREIGN KEY (employee_nrp) REFERENCES tbl_m_employee_profiles (nrp)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_geofence_setting') THEN
                        ALTER TABLE tbl_m_attendance_geofence_points
                        ADD CONSTRAINT fk_attendance_geofence_setting
                        FOREIGN KEY (attendance_setting_id) REFERENCES tbl_m_attendance_settings (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_logs_user') THEN
                        ALTER TABLE tbl_t_attendance_logs
                        ADD CONSTRAINT fk_attendance_logs_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_leave_requests_user') THEN
                        ALTER TABLE tbl_t_leave_requests
                        ADD CONSTRAINT fk_leave_requests_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_leave_requests_approved_by') THEN
                        ALTER TABLE tbl_t_leave_requests
                        ADD CONSTRAINT fk_leave_requests_approved_by
                        FOREIGN KEY (approved_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_overtime_requests_user') THEN
                        ALTER TABLE tbl_t_overtime_requests
                        ADD CONSTRAINT fk_overtime_requests_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_overtime_requests_approved_by') THEN
                        ALTER TABLE tbl_t_overtime_requests
                        ADD CONSTRAINT fk_overtime_requests_approved_by
                        FOREIGN KEY (approved_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sales_daily_targets_user') THEN
                        ALTER TABLE tbl_t_sales_daily_targets
                        ADD CONSTRAINT fk_sales_daily_targets_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sales_daily_targets_created_by') THEN
                        ALTER TABLE tbl_t_sales_daily_targets
                        ADD CONSTRAINT fk_sales_daily_targets_created_by
                        FOREIGN KEY (created_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_store_submissions_sales_user') THEN
                        ALTER TABLE tbl_t_store_submissions
                        ADD CONSTRAINT fk_store_submissions_sales_user
                        FOREIGN KEY (sales_user_id) REFERENCES tbl_m_users (id)
                        ON DELETE RESTRICT
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_store_submissions_checkpoint') THEN
                        ALTER TABLE tbl_t_store_submissions
                        ADD CONSTRAINT fk_store_submissions_checkpoint
                        FOREIGN KEY (approved_checkpoint_id) REFERENCES tbl_m_checkpoints (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_store_submissions_approved_by') THEN
                        ALTER TABLE tbl_t_store_submissions
                        ADD CONSTRAINT fk_store_submissions_approved_by
                        FOREIGN KEY (approved_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sales_visits_source_submission') THEN
                        ALTER TABLE tbl_t_sales_visits
                        ADD CONSTRAINT fk_sales_visits_source_submission
                        FOREIGN KEY (source_submission_id) REFERENCES tbl_t_store_submissions (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visit_schedule_user') THEN
                        ALTER TABLE tbl_t_sales_visit_schedules
                        ADD CONSTRAINT fk_visit_schedule_user
                        FOREIGN KEY (user_id) REFERENCES tbl_m_users (id)
                        ON DELETE CASCADE
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visit_schedule_checkpoint') THEN
                        ALTER TABLE tbl_t_sales_visit_schedules
                        ADD CONSTRAINT fk_visit_schedule_checkpoint
                        FOREIGN KEY (checkpoint_id) REFERENCES tbl_m_checkpoints (id)
                        ON DELETE RESTRICT
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visit_schedule_created_by') THEN
                        ALTER TABLE tbl_t_sales_visit_schedules
                        ADD CONSTRAINT fk_visit_schedule_created_by
                        FOREIGN KEY (created_by) REFERENCES tbl_m_users (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecSafeAsync(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visit_schedule_source_submission') THEN
                        ALTER TABLE tbl_t_sales_visit_schedules
                        ADD CONSTRAINT fk_visit_schedule_source_submission
                        FOREIGN KEY (source_submission_id) REFERENCES tbl_t_store_submissions (id)
                        ON DELETE SET NULL
                        NOT VALID;
                    END IF;
                END
                $$;
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_sales_visit_reports (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL REFERENCES tbl_m_users(id) ON DELETE CASCADE,
                    checkpoint_id integer NOT NULL REFERENCES tbl_m_checkpoints(id) ON DELETE RESTRICT,
                    report_date date NOT NULL,
                    visit_status varchar(30) NOT NULL DEFAULT 'completed',
                    outcome varchar(200) NULL,
                    notes varchar(500) NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_payroll_auto_sends (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    payroll_period varchar(20) NOT NULL,
                    send_date date NOT NULL,
                    status varchar(30) NOT NULL DEFAULT 'scheduled',
                    recipient_count integer NOT NULL DEFAULT 0,
                    notes varchar(500) NULL,
                    sent_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_work_arrangement_requests (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL REFERENCES tbl_m_users(id) ON DELETE CASCADE,
                    request_date date NOT NULL,
                    work_date_from date NOT NULL,
                    work_date_to date NOT NULL,
                    arrangement_type varchar(10) NOT NULL DEFAULT 'WFH',
                    location varchar(200) NULL,
                    reason varchar(500) NULL,
                    status varchar(30) NOT NULL DEFAULT 'pending',
                    approved_by integer NULL REFERENCES tbl_m_users(id) ON DELETE SET NULL,
                    approved_at timestamp NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_sales_target_compliances (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL REFERENCES tbl_m_users(id) ON DELETE CASCADE,
                    compliance_date date NOT NULL,
                    target_visits integer NOT NULL DEFAULT 0,
                    actual_visits integer NOT NULL DEFAULT 0,
                    compliance_percent double precision NOT NULL DEFAULT 0,
                    status varchar(30) NOT NULL DEFAULT 'watch',
                    notes varchar(500) NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_recruitment_candidates (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    candidate_name varchar(150) NOT NULL,
                    email varchar(120) NULL,
                    phone varchar(30) NULL,
                    position_applied varchar(100) NULL,
                    stage varchar(50) NOT NULL DEFAULT 'Screening',
                    status varchar(30) NOT NULL DEFAULT 'active',
                    source varchar(80) NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_onboarding_tasks (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    candidate_id integer NULL REFERENCES tbl_t_recruitment_candidates(id) ON DELETE SET NULL,
                    employee_name varchar(150) NOT NULL,
                    task_name varchar(150) NOT NULL,
                    due_date date NOT NULL,
                    status varchar(30) NOT NULL DEFAULT 'open',
                    owner_name varchar(100) NULL,
                    notes varchar(500) NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecRequiredAsync(@"
                CREATE TABLE IF NOT EXISTS tbl_t_cv_master_summaries (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    candidate_id integer NULL REFERENCES tbl_t_recruitment_candidates(id) ON DELETE SET NULL,
                    candidate_name varchar(150) NOT NULL,
                    position varchar(100) NULL,
                    last_education varchar(100) NULL,
                    years_experience integer NOT NULL DEFAULT 0,
                    skills varchar(500) NULL,
                    summary varchar(1000) NULL,
                    score integer NOT NULL DEFAULT 0,
                    created_at timestamp NOT NULL DEFAULT now()
                );
            ");

            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_visit_reports_date_user ON tbl_t_sales_visit_reports (report_date, user_id);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_work_arrangements_status ON tbl_t_work_arrangement_requests (status, work_date_from);");
            await ExecSafeAsync(@"CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_compliance_user_date ON tbl_t_sales_target_compliances (user_id, compliance_date);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_recruitment_stage_status ON tbl_t_recruitment_candidates (stage, status);");
            await ExecSafeAsync(@"CREATE INDEX IF NOT EXISTS ix_onboarding_status_due ON tbl_t_onboarding_tasks (status, due_date);");

                // Mark schema version as done — DDL will NOT run again on next startup
                await ExecRequiredAsync(
                    $"INSERT INTO tbl_schema_version (version) VALUES ('{SchemaVersion}') ON CONFLICT DO NOTHING");
                Console.WriteLine($"[DbSeeder] Schema {SchemaVersion} applied successfully.");
            }
            else
            {
                Console.WriteLine($"[DbSeeder] Schema {SchemaVersion} already applied, skipping DDL.");
            }

            // ── Data seed (always runs, but each check is a single fast query) ─

            // --- Roles ---
            if (!await db.Roles.AnyAsync())
            {
                var roles = new List<Role>
                {
                    new() { RoleName = "Administrator", Description = "Full akses sistem", IsActive = true },
                    new() { RoleName = "Sales",         Description = "Sales representative",  IsActive = true },
                    new() { RoleName = "Pengawas",      Description = "Supervisor / pengawas sales", IsActive = true }
                };
                await db.Roles.AddRangeAsync(roles);
                await db.SaveChangesAsync();
            }

            // --- Menus ---
            if (!await db.Menus.AnyAsync())
            {
                var menus = new List<Menu>
                {
                    new() { MenuName = "Dashboard",         MenuUrl = "/Home/Index",                   IconClass = "fas fa-tachometer-alt", SortOrder = 1,  ParentId = null },
                    new() { MenuName = "Tracking Sales",    MenuUrl = "#",                             IconClass = "fas fa-map-marked-alt", SortOrder = 2,  ParentId = null },
                    new() { MenuName = "Live Tracking",     MenuUrl = "/SalesTracking/Index",          IconClass = "fas fa-satellite-dish", SortOrder = 3,  ParentId = null },
                    new() { MenuName = "Riwayat Kunjungan", MenuUrl = "/SalesTracking/History",        IconClass = "fas fa-history",        SortOrder = 4,  ParentId = null },
                    new() { MenuName = "Checkpoint",        MenuUrl = "#",                             IconClass = "fas fa-map-pin",        SortOrder = 5,  ParentId = null },
                    new() { MenuName = "Daftar Checkpoint", MenuUrl = "/Checkpoint/Index",             IconClass = "fas fa-list",           SortOrder = 6,  ParentId = null },
                    new() { MenuName = "Peta Checkpoint",   MenuUrl = "/Checkpoint/Map",               IconClass = "fas fa-map",            SortOrder = 7,  ParentId = null },
                    new() { MenuName = "Administrasi",      MenuUrl = "#",                             IconClass = "fas fa-cogs",           SortOrder = 8,  ParentId = null },
                    new() { MenuName = "Manajemen User",    MenuUrl = "/User/Index",                   IconClass = "fas fa-users",          SortOrder = 9,  ParentId = null },
                    new() { MenuName = "Manajemen Role",    MenuUrl = "/Role/Index",                   IconClass = "fas fa-user-shield",    SortOrder = 10, ParentId = null },
                    new() { MenuName = "Manajemen Menu",    MenuUrl = "/MenuAdmin/Index",              IconClass = "fas fa-bars",           SortOrder = 11, ParentId = null },
                    new() { MenuName = "Akses Role-Menu",   MenuUrl = "/Role/AccessMenu",              IconClass = "fas fa-key",            SortOrder = 12, ParentId = null },
                };
                await db.Menus.AddRangeAsync(menus);
                await db.SaveChangesAsync();
            }

            // Ensure mobile user menu exists.
            var mobileMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "/MUser/Index");
            if (mobileMenu == null)
            {
                var nextSort = (await db.Menus.MaxAsync(m => (int?)m.SortOrder) ?? 0) + 1;
                mobileMenu = new Menu
                {
                    MenuName = "User Mobile",
                    MenuUrl = "/MUser/Index",
                    IconClass = "fas fa-mobile-alt",
                    SortOrder = nextSort,
                    ParentId = null,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(mobileMenu);
                await db.SaveChangesAsync();
            }

            // Ensure daily target menu exists.
            var dailyTargetMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "/SalesTarget/Index");
            if (dailyTargetMenu == null)
            {
                var nextSort = (await db.Menus.MaxAsync(m => (int?)m.SortOrder) ?? 0) + 1;
                dailyTargetMenu = new Menu
                {
                    MenuName = "Target Harian Sales",
                    MenuUrl = "/SalesTarget/Index",
                    IconClass = "fas fa-bullseye",
                    SortOrder = nextSort,
                    ParentId = null,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(dailyTargetMenu);
                await db.SaveChangesAsync();
            }

            var payrollMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "#" && (m.MenuName == "Payroll" || m.MenuName == "Payroll & Attendance" || m.MenuName == "HR & Payroll"));
            if (payrollMenu == null)
            {
                var nextSort = (await db.Menus.MaxAsync(m => (int?)m.SortOrder) ?? 0) + 1;
                payrollMenu = new Menu
                {
                    MenuName = "HR & Payroll",
                    MenuUrl = "#",
                    IconClass = "fas fa-id-card-alt",
                    SortOrder = nextSort,
                    ParentId = null,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(payrollMenu);
                await db.SaveChangesAsync();
            }
            else
            {
                payrollMenu.MenuName = "HR & Payroll";
                payrollMenu.IconClass = "fas fa-id-card-alt";
                payrollMenu.IsActive = true;
                await db.SaveChangesAsync();
            }

            async Task<Menu> EnsurePayrollChild(string name, string url, string icon, int order)
            {
                var exists = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == url);
                if (exists != null)
                {
                    exists.MenuName = name;
                    exists.IconClass = icon;
                    exists.SortOrder = order;
                    exists.ParentId = payrollMenu!.Id;
                    exists.IsActive = true;
                    await db.SaveChangesAsync();
                    return exists;
                }
                var menu = new Menu
                {
                    MenuName = name,
                    MenuUrl = url,
                    IconClass = icon,
                    SortOrder = order,
                    ParentId = payrollMenu!.Id,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(menu);
                await db.SaveChangesAsync();
                return menu;
            }

            var attendanceSettingsMenu = await EnsurePayrollChild("Lokasi Absensi", "/Payroll/AttendanceSettings", "fas fa-map-marked-alt", payrollMenu.SortOrder + 1);
            var attendanceReportMenu = await EnsurePayrollChild("Laporan Absensi", "/Payroll/AttendanceReport", "fas fa-file-alt", payrollMenu.SortOrder + 2);
            var leaveOvertimeMenu = await EnsurePayrollChild("Izin & Lembur", "/Payroll/LeaveOvertime", "fas fa-user-clock", payrollMenu.SortOrder + 3);

            async Task<Menu> EnsureRootMenu(string name, string url, string icon, int order, params string[] oldNames)
            {
                var names = oldNames.Append(name).Distinct().ToList();
                var menu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == url && names.Contains(m.MenuName));
                if (menu != null)
                {
                    menu.MenuName = name;
                    menu.IconClass = icon;
                    menu.SortOrder = order;
                    menu.ParentId = null;
                    menu.IsActive = true;
                    await db.SaveChangesAsync();
                    return menu;
                }

                menu = new Menu
                {
                    MenuName = name,
                    MenuUrl = url,
                    IconClass = icon,
                    SortOrder = order,
                    ParentId = null,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(menu);
                await db.SaveChangesAsync();
                return menu;
            }

            async Task<Menu> EnsureChildMenu(Menu parent, string name, string url, string icon, int order)
            {
                var menu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == url);
                if (menu == null)
                {
                    menu = new Menu
                    {
                        MenuName = name,
                        MenuUrl = url,
                        IconClass = icon,
                        SortOrder = order,
                        ParentId = parent.Id,
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    };
                    await db.Menus.AddAsync(menu);
                }
                else
                {
                    menu.MenuName = name;
                    menu.IconClass = icon;
                    menu.ParentId = parent.Id;
                    menu.IsActive = true;
                }
                await db.SaveChangesAsync();
                return menu;
            }

            var controlCenterMenu = await EnsureRootMenu("Operational Control", "#", "fas fa-shield-alt", 2, "Control Center");
            var trackingMenu = await EnsureRootMenu("Field Operations", "#", "fas fa-map-marked-alt", 5, "Tracking Sales", "Sales Tracking");
            var salesReportMenu = await EnsureRootMenu("Sales Reports", "#", "fas fa-chart-bar", 8, "Sales Report");
            var salesPlanningMenu = await EnsureRootMenu("Sales Planning", "#", "fas fa-calendar-alt", 11);
            var checkpointMenu = await EnsureRootMenu("Checkpoint & Territory", "#", "fas fa-map-pin", 14, "Checkpoint");
            var talentMenu = await EnsureRootMenu("Talent Management", "#", "fas fa-user-tie", 23);
            var appSettingsMenu = await EnsureRootMenu("Application Settings", "#", "fas fa-cogs", 27, "Administrasi");
            var liveTrackingMenu = await EnsureChildMenu(trackingMenu, "Live Tracking", "/SalesTracking/Index", "fas fa-satellite-dish", 6);
            var visitHistoryMenu = await EnsureChildMenu(trackingMenu, "Riwayat Kunjungan", "/SalesTracking/History", "fas fa-history", 7);
            var visitReportMenu = await EnsureChildMenu(salesReportMenu, "Laporan Kunjungan", "/SalesVisitReport/Index", "fas fa-clipboard-check", 9);
            var complianceMenu = await EnsureChildMenu(salesReportMenu, "Compliance Target", "/SalesCompliance/Index", "fas fa-chart-line", 10);
            var checkpointListMenu = await EnsureChildMenu(checkpointMenu, "Daftar Checkpoint", "/Checkpoint/Index", "fas fa-list", 15);
            var checkpointMapMenu = await EnsureChildMenu(checkpointMenu, "Peta Checkpoint", "/Checkpoint/Map", "fas fa-map", 16);
            var payrollAutoMenu = await EnsureChildMenu(payrollMenu, "Kirim Payroll Otomatis", "/PayrollAutoSend/Index", "fas fa-paper-plane", 21);
            var workArrangementMenu = await EnsureChildMenu(payrollMenu, "Pengajuan WFH/WFA", "/WorkArrangement/Index", "fas fa-laptop-house", 22);
            var recruitmentMenu = await EnsureChildMenu(talentMenu, "Rekrutmen", "/Recruitment/Index", "fas fa-user-plus", 24);
            var onboardingMenu = await EnsureChildMenu(talentMenu, "Onboarding", "/Onboarding/Index", "fas fa-people-arrows", 25);
            var cvSummaryMenu = await EnsureChildMenu(talentMenu, "Ringkasan CV", "/CvSummary/Index", "fas fa-id-badge", 26);
            var webUserMenu = await EnsureChildMenu(appSettingsMenu, "User Web", "/User/Index", "fas fa-users", 28);
            var mobileUserMenu = await EnsureChildMenu(appSettingsMenu, "User Mobile", "/MUser/Index", "fas fa-mobile-alt", 29);
            var roleMenu = await EnsureChildMenu(appSettingsMenu, "Role & Permission", "/Role/Index", "fas fa-user-shield", 30);
            var accessMenu = await EnsureChildMenu(appSettingsMenu, "Akses Role Menu", "/Role/AccessMenu", "fas fa-key", 31);
            var menuBuilderMenu = await EnsureChildMenu(appSettingsMenu, "Menu Builder", "/MenuAdmin/Index", "fas fa-bars", 32);

            var scheduleMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "/SalesSchedule/Index");
            if (scheduleMenu == null)
            {
                var nextSort = (await db.Menus.MaxAsync(m => (int?)m.SortOrder) ?? 0) + 1;
                scheduleMenu = new Menu
                {
                    MenuName = "Jadwal Kunjungan",
                    MenuUrl = "/SalesSchedule/Index",
                    IconClass = "fas fa-calendar-check",
                    SortOrder = nextSort,
                    ParentId = salesPlanningMenu.Id,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };
                await db.Menus.AddAsync(scheduleMenu);
                await db.SaveChangesAsync();
            }
            else
            {
                scheduleMenu.MenuName = "Jadwal Kunjungan";
                scheduleMenu.ParentId = salesPlanningMenu.Id;
                scheduleMenu.IconClass = "fas fa-calendar-check";
                scheduleMenu.IsActive = true;
                await db.SaveChangesAsync();
            }

            dailyTargetMenu.MenuName = "Target Harian";
            dailyTargetMenu.ParentId = salesPlanningMenu.Id;
            dailyTargetMenu.IconClass = "fas fa-bullseye";
            await db.SaveChangesAsync();

            var approvalCenterMenu = await EnsureChildMenu(controlCenterMenu, "Approval Center", "/Approval/Index", "fas fa-tasks", 3);
            var auditMenu = await EnsureChildMenu(controlCenterMenu, "Audit Trail", "/Audit/Index", "fas fa-clipboard-list", 4);

            // Merge duplicate feature menus by URL to prevent duplicate UI entries.
            var duplicatedUrlGroups = (await db.Menus
                .Where(m => !string.IsNullOrEmpty(m.MenuUrl) && m.MenuUrl != "#")
                .ToListAsync())
                .GroupBy(m => m.MenuUrl!)
                .Where(g => g.Count() > 1)
                .ToList();
            foreach (var grp in duplicatedUrlGroups)
            {
                var ordered = grp.OrderBy(m => m.Id).ToList();
                var keeper = ordered.First();
                var duplicates = ordered.Skip(1).ToList();

                foreach (var dup in duplicates)
                {
                    var roleMenus = await db.RoleMenus.Where(rm => rm.MenuId == dup.Id).ToListAsync();
                    foreach (var rm in roleMenus)
                    {
                        var exists = await db.RoleMenus.AnyAsync(x => x.RoleId == rm.RoleId && x.MenuId == keeper.Id);
                        if (!exists)
                            rm.MenuId = keeper.Id;
                        else
                            db.RoleMenus.Remove(rm);
                    }

                    // Re-link child menus to keeper when needed.
                    var childMenus = await db.Menus.Where(m => m.ParentId == dup.Id).ToListAsync();
                    foreach (var child in childMenus) child.ParentId = keeper.Id;

                    dup.IsActive = false;
                }
                await db.SaveChangesAsync();
            }

            // Merge duplicate heading menus (MenuUrl '#') by MenuName.
            var duplicatedHeadingGroups = (await db.Menus
                .Where(m => m.MenuUrl == "#")
                .ToListAsync())
                .GroupBy(m => m.MenuName)
                .Where(g => g.Count() > 1)
                .ToList();
            foreach (var grp in duplicatedHeadingGroups)
            {
                var ordered = grp.OrderBy(m => m.Id).ToList();
                var keeper = ordered.First();
                var duplicates = ordered.Skip(1).ToList();
                foreach (var dup in duplicates)
                {
                    var childMenus = await db.Menus.Where(m => m.ParentId == dup.Id).ToListAsync();
                    foreach (var child in childMenus) child.ParentId = keeper.Id;
                    dup.IsActive = false;
                }
                await db.SaveChangesAsync();
            }

            // Normalize sidebar ordering to keep modules grouped and consistent.
            async Task SetSortOrderAsync(string? menuUrl, string? menuName, int sortOrder)
            {
                var m = await db.Menus.FirstOrDefaultAsync(x =>
                    (menuUrl != null && x.MenuUrl == menuUrl) ||
                    (menuName != null && x.MenuName == menuName));
                if (m != null && m.SortOrder != sortOrder)
                {
                    m.SortOrder = sortOrder;
                    await db.SaveChangesAsync();
                }
            }

            await SetSortOrderAsync("/Home/Index", null, 1);
            await SetSortOrderAsync("#", "Operational Control", 2);
            await SetSortOrderAsync("/Approval/Index", null, 3);
            await SetSortOrderAsync("/Audit/Index", null, 4);
            await SetSortOrderAsync("#", "Field Operations", 5);
            await SetSortOrderAsync("/SalesTracking/Index", null, 6);
            await SetSortOrderAsync("/SalesTracking/History", null, 7);
            await SetSortOrderAsync("#", "Sales Reports", 8);
            await SetSortOrderAsync("/SalesVisitReport/Index", null, 9);
            await SetSortOrderAsync("/SalesCompliance/Index", null, 10);
            await SetSortOrderAsync("#", "Sales Planning", 11);
            await SetSortOrderAsync("/SalesTarget/Index", null, 12);
            await SetSortOrderAsync("/SalesSchedule/Index", null, 13);
            await SetSortOrderAsync("#", "Checkpoint & Territory", 14);
            await SetSortOrderAsync("/Checkpoint/Index", null, 15);
            await SetSortOrderAsync("/Checkpoint/Map", null, 16);
            await SetSortOrderAsync("#", "HR & Payroll", 17);
            await SetSortOrderAsync("/Payroll/AttendanceSettings", null, 18);
            await SetSortOrderAsync("/Payroll/AttendanceReport", null, 19);
            await SetSortOrderAsync("/Payroll/LeaveOvertime", null, 20);
            await SetSortOrderAsync("/PayrollAutoSend/Index", null, 21);
            await SetSortOrderAsync("/WorkArrangement/Index", null, 22);
            await SetSortOrderAsync("#", "Talent Management", 23);
            await SetSortOrderAsync("/Recruitment/Index", null, 24);
            await SetSortOrderAsync("/Onboarding/Index", null, 25);
            await SetSortOrderAsync("/CvSummary/Index", null, 26);
            await SetSortOrderAsync("#", "Application Settings", 27);
            await SetSortOrderAsync("/User/Index", null, 28);
            await SetSortOrderAsync("/MUser/Index", null, 29);
            await SetSortOrderAsync("/Role/Index", null, 30);
            await SetSortOrderAsync("/Role/AccessMenu", null, 31);
            await SetSortOrderAsync("/MenuAdmin/Index", null, 32);

            // --- Admin user ---
            if (!await db.Users.AnyAsync())
            {
                var admin = new User
                {
                    Username = "admin",
                    Password = "admin",
                    FullName = "Administrator",
                    Email = "admin@navsnap.com",
                    IsActive = true
                };
                await db.Users.AddAsync(admin);
                await db.SaveChangesAsync();

                var adminRole = await db.Roles.FirstAsync(r => r.RoleName == "Administrator");
                await db.UserRoles.AddAsync(new UserRole { UserId = admin.Id, RoleId = adminRole.Id });
                await db.SaveChangesAsync();

                // Assign all menus to Administrator
                var allMenuIds = await db.Menus.Select(m => m.Id).ToListAsync();
                var roleMenus = allMenuIds.Select(mid => new RoleMenu { RoleId = adminRole.Id, MenuId = mid });
                await db.RoleMenus.AddRangeAsync(roleMenus);
                await db.SaveChangesAsync();

                // Sales role: dashboard + tracking + checkpoint view
                var salesRole = await db.Roles.FirstAsync(r => r.RoleName == "Sales");
                var salesMenuIds = await db.Menus
                    .Where(m => m.MenuUrl == "/Home/Index" ||
                                m.MenuUrl == "/SalesTracking/Index" ||
                                m.MenuUrl == "/Checkpoint/Index")
                    .Select(m => m.Id).ToListAsync();
                await db.RoleMenus.AddRangeAsync(salesMenuIds.Select(mid => new RoleMenu { RoleId = salesRole.Id, MenuId = mid }));

                // Pengawas role: dashboard + tracking + checkpoint
                var pengawasRole = await db.Roles.FirstAsync(r => r.RoleName == "Pengawas");
                var pengawasMenuIds = await db.Menus
                    .Where(m => m.MenuUrl == "/Home/Index" ||
                                m.MenuUrl == "/SalesTracking/Index" ||
                                m.MenuUrl == "/SalesTracking/History" ||
                                m.MenuUrl == "/Checkpoint/Index" ||
                                m.MenuUrl == "/Checkpoint/Map")
                    .Select(m => m.Id).ToListAsync();
                await db.RoleMenus.AddRangeAsync(pengawasMenuIds.Select(mid => new RoleMenu { RoleId = pengawasRole.Id, MenuId = mid }));

                await db.SaveChangesAsync();
            }

            // Ensure Administrator has access to mobile user menu.
            var adminRoleExisting = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Administrator");
            if (adminRoleExisting != null && mobileMenu != null)
            {
                var hasAccess = await db.RoleMenus.AnyAsync(rm => rm.RoleId == adminRoleExisting.Id && rm.MenuId == mobileMenu.Id);
                if (!hasAccess)
                {
                    await db.RoleMenus.AddAsync(new RoleMenu
                    {
                        RoleId = adminRoleExisting.Id,
                        MenuId = mobileMenu.Id
                    });
                    await db.SaveChangesAsync();
                }
            }

            // Ensure Administrator and Pengawas can access daily target settings.
            if (dailyTargetMenu != null)
            {
                var adminRole = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Administrator");
                if (adminRole != null)
                {
                    var adminHas = await db.RoleMenus.AnyAsync(rm => rm.RoleId == adminRole.Id && rm.MenuId == dailyTargetMenu.Id);
                    if (!adminHas)
                    {
                        await db.RoleMenus.AddAsync(new RoleMenu { RoleId = adminRole.Id, MenuId = dailyTargetMenu.Id });
                        await db.SaveChangesAsync();
                    }
                }

                var pengawasRole = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Pengawas");
                if (pengawasRole != null)
                {
                    var pengawasHas = await db.RoleMenus.AnyAsync(rm => rm.RoleId == pengawasRole.Id && rm.MenuId == dailyTargetMenu.Id);
                    if (!pengawasHas)
                    {
                        await db.RoleMenus.AddAsync(new RoleMenu { RoleId = pengawasRole.Id, MenuId = dailyTargetMenu.Id });
                        await db.SaveChangesAsync();
                    }
                }
            }

            var scheduleAccessMenu = await db.Menus.FirstOrDefaultAsync(m => m.MenuUrl == "/SalesSchedule/Index");
            if (scheduleAccessMenu != null)
            {
                async Task EnsureSingleMenu(string roleName, int menuId)
                {
                    var role = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == roleName);
                    if (role == null) return;
                    var has = await db.RoleMenus.AnyAsync(rm => rm.RoleId == role.Id && rm.MenuId == menuId);
                    if (!has)
                    {
                        await db.RoleMenus.AddAsync(new RoleMenu { RoleId = role.Id, MenuId = menuId });
                        await db.SaveChangesAsync();
                    }
                }

                await EnsureSingleMenu("Administrator", scheduleAccessMenu.Id);
                await EnsureSingleMenu("Pengawas", scheduleAccessMenu.Id);
            }

            // Ensure payroll menus access by role.
            if (payrollMenu != null)
            {
                var payrollMenuIds = await db.Menus
                    .Where(m => m.Id == payrollMenu.Id || m.ParentId == payrollMenu.Id)
                    .Select(m => m.Id)
                    .ToListAsync();

                async Task EnsureRoleMenus(string roleName)
                {
                    var role = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == roleName);
                    if (role == null) return;
                    foreach (var mid in payrollMenuIds)
                    {
                        var has = await db.RoleMenus.AnyAsync(rm => rm.RoleId == role.Id && rm.MenuId == mid);
                        if (!has)
                            await db.RoleMenus.AddAsync(new RoleMenu { RoleId = role.Id, MenuId = mid });
                    }
                    await db.SaveChangesAsync();
                }

                await EnsureRoleMenus("Administrator");
                await EnsureRoleMenus("Pengawas");
                await EnsureRoleMenus("Sales");
            }

            async Task EnsureRoleMenuAccess(string roleName, params Menu?[] menusToGrant)
            {
                var role = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == roleName);
                if (role == null) return;

                foreach (var menu in menusToGrant.OfType<Menu>())
                {
                    var has = await db.RoleMenus.AnyAsync(rm => rm.RoleId == role.Id && rm.MenuId == menu.Id);
                    if (!has)
                        await db.RoleMenus.AddAsync(new RoleMenu { RoleId = role.Id, MenuId = menu.Id });
                }
                await db.SaveChangesAsync();
            }

            await EnsureRoleMenuAccess("Administrator",
                controlCenterMenu, approvalCenterMenu, auditMenu,
                trackingMenu, liveTrackingMenu, visitHistoryMenu,
                salesReportMenu, visitReportMenu, complianceMenu,
                salesPlanningMenu, dailyTargetMenu, scheduleMenu,
                checkpointMenu, checkpointListMenu, checkpointMapMenu,
                payrollMenu, attendanceSettingsMenu, attendanceReportMenu, leaveOvertimeMenu,
                payrollAutoMenu, workArrangementMenu,
                talentMenu, recruitmentMenu, onboardingMenu, cvSummaryMenu,
                appSettingsMenu, webUserMenu, mobileUserMenu, roleMenu, accessMenu, menuBuilderMenu);
            await EnsureRoleMenuAccess("Pengawas",
                controlCenterMenu, approvalCenterMenu, auditMenu,
                trackingMenu, liveTrackingMenu, visitHistoryMenu,
                salesReportMenu, visitReportMenu, complianceMenu,
                salesPlanningMenu, dailyTargetMenu, scheduleMenu,
                checkpointMenu, checkpointListMenu, checkpointMapMenu,
                payrollMenu, attendanceReportMenu, payrollAutoMenu, workArrangementMenu,
                talentMenu, recruitmentMenu, onboardingMenu, cvSummaryMenu);
            await EnsureRoleMenuAccess("Sales",
                trackingMenu, liveTrackingMenu, visitHistoryMenu,
                salesReportMenu, visitReportMenu,
                checkpointMenu, checkpointListMenu,
                payrollMenu, workArrangementMenu);

            // --- Dummy transaksi & pergerakan (10 data) ---
            var adminUser = await db.Users.FirstOrDefaultAsync(u => u.Username == "admin");
            var salesRoleExisting = await db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Sales");
            if (adminUser != null && salesRoleExisting != null)
            {
                var dummyEmployees = new[]
                {
                    new { Nrp = "NRP1001", Nama = "Andi Saputra", Jabatan = "Sales Executive", Divisi = "Retail GT", Alamat = "Makassar" },
                    new { Nrp = "NRP1002", Nama = "Budi Hartono", Jabatan = "Sales Executive", Divisi = "Retail GT", Alamat = "Makassar" },
                    new { Nrp = "NRP1003", Nama = "Citra Lestari", Jabatan = "Merchandiser", Divisi = "Modern Trade", Alamat = "Gowa" },
                    new { Nrp = "NRP1004", Nama = "Dewi Kartika", Jabatan = "Area Sales", Divisi = "Distribusi", Alamat = "Maros" },
                    new { Nrp = "NRP1005", Nama = "Eko Prasetyo", Jabatan = "Sales Executive", Divisi = "Retail GT", Alamat = "Makassar" },
                    new { Nrp = "NRP1006", Nama = "Fajar Ramadhan", Jabatan = "Sales Executive", Divisi = "Retail GT", Alamat = "Makassar" },
                    new { Nrp = "NRP1007", Nama = "Gina Maharani", Jabatan = "Merchandiser", Divisi = "Modern Trade", Alamat = "Takalar" },
                    new { Nrp = "NRP1008", Nama = "Hadi Nugraha", Jabatan = "Area Sales", Divisi = "Distribusi", Alamat = "Makassar" },
                    new { Nrp = "NRP1009", Nama = "Intan Permata", Jabatan = "Sales Executive", Divisi = "Retail GT", Alamat = "Gowa" },
                    new { Nrp = "NRP1010", Nama = "Joko Susilo", Jabatan = "Sales Executive", Divisi = "Retail GT", Alamat = "Makassar" }
                };

                foreach (var emp in dummyEmployees)
                {
                    if (!await db.EmployeeProfiles.AnyAsync(e => e.Nrp == emp.Nrp))
                    {
                        await db.EmployeeProfiles.AddAsync(new EmployeeProfile
                        {
                            Nrp = emp.Nrp,
                            FullName = emp.Nama,
                            FullAddress = $"Jl. Contoh {emp.Nrp}, {emp.Alamat}",
                            JobTitle = emp.Jabatan,
                            Position = emp.Jabatan,
                            Division = emp.Divisi,
                            Department = "Sales",
                            Phone = $"08{emp.Nrp[^4..]}12345",
                            Email = $"{emp.Nrp.ToLower()}@navsnap.id",
                            IsActive = true,
                            CreatedAt = DateTime.UtcNow
                        });
                    }

                    if (!await db.MUsers.AnyAsync(m => m.Nrp == emp.Nrp))
                    {
                        await db.MUsers.AddAsync(new MUser
                        {
                            Nrp = emp.Nrp,
                            User = emp.Nrp.ToLower(),
                            Password = "123456",
                            Status = true,
                            TerakhirLogin = DateTime.UtcNow.AddHours(-new Random(emp.Nrp.GetHashCode()).Next(2, 48)),
                            PathFotoProfile = $"/images/profiles/{emp.Nrp.ToLower()}.jpg",
                            EmployeeNrp = emp.Nrp
                        });
                    }
                }
                await db.SaveChangesAsync();

                var salesUsers = new List<User>();
                for (int i = 1; i <= 10; i++)
                {
                    var uname = $"sales{i:00}";
                    var existingUser = await db.Users.FirstOrDefaultAsync(u => u.Username == uname);
                    if (existingUser == null)
                    {
                        existingUser = new User
                        {
                            Username = uname,
                            Password = "123456",
                            FullName = dummyEmployees[i - 1].Nama,
                            Email = $"{uname}@navsnap.id",
                            Phone = $"08124{i:00000}",
                            IsActive = true,
                            CreatedAt = DateTime.UtcNow.AddDays(-15 + i)
                        };
                        await db.Users.AddAsync(existingUser);
                        await db.SaveChangesAsync();
                    }

                    var hasRole = await db.UserRoles.AnyAsync(ur => ur.UserId == existingUser.Id && ur.RoleId == salesRoleExisting.Id);
                    if (!hasRole)
                    {
                        await db.UserRoles.AddAsync(new UserRole
                        {
                            UserId = existingUser.Id,
                            RoleId = salesRoleExisting.Id
                        });
                        await db.SaveChangesAsync();
                    }

                    salesUsers.Add(existingUser);
                }

                var dummyStores = new[]
                {
                    new { Nama = "Toko Maju Jaya Panakkukang", Alamat = "Jl. Boulevard Panakkukang", Lat = -5.1476, Lng = 119.4327 },
                    new { Nama = "Toko Sinar Rejeki Tamalanrea", Alamat = "Jl. Perintis Kemerdekaan", Lat = -5.1262, Lng = 119.4892 },
                    new { Nama = "Toko Berkah Mandiri Rappocini", Alamat = "Jl. Aroepala", Lat = -5.1688, Lng = 119.4476 },
                    new { Nama = "Toko Nusantara Makmur Biringkanaya", Alamat = "Jl. Daya", Lat = -5.1117, Lng = 119.5251 },
                    new { Nama = "Toko Cahaya Baru Ujung Pandang", Alamat = "Jl. Penghibur", Lat = -5.1358, Lng = 119.4062 },
                    new { Nama = "Toko Mitra Sentosa Mariso", Alamat = "Jl. Metro Tanjung Bunga", Lat = -5.1604, Lng = 119.3922 },
                    new { Nama = "Toko Prima Grosir Manggala", Alamat = "Jl. Antang Raya", Lat = -5.1804, Lng = 119.4874 },
                    new { Nama = "Toko Bintang Timur Somba Opu", Alamat = "Jl. Andi Tonro", Lat = -5.1822, Lng = 119.4247 },
                    new { Nama = "Toko Sejahtera Abadi Bontoala", Alamat = "Jl. Tinumbu", Lat = -5.1269, Lng = 119.4269 },
                    new { Nama = "Toko Cemerlang Mandai", Alamat = "Jl. Poros Makassar Maros", Lat = -5.0589, Lng = 119.5663 }
                };

                var checkpoints = new List<Checkpoint>();
                for (int i = 0; i < dummyStores.Length; i++)
                {
                    var store = dummyStores[i];
                    var cp = await db.Checkpoints.FirstOrDefaultAsync(c => c.CheckpointName == store.Nama);
                    if (cp == null)
                    {
                        cp = new Checkpoint
                        {
                            CheckpointName = store.Nama,
                            Address = store.Alamat,
                            Latitude = store.Lat,
                            Longitude = store.Lng,
                            RadiusMeters = 120,
                            IsActive = true,
                            CreatedBy = adminUser.Id,
                            CreatedAt = DateTime.UtcNow.AddDays(-10 + i)
                        };
                        await db.Checkpoints.AddAsync(cp);
                        await db.SaveChangesAsync();
                    }
                    checkpoints.Add(cp);
                }

                var baseDate = DateOnly.FromDateTime(DateTime.Today.AddDays(-9));

                for (int i = 0; i < 10; i++)
                {
                    var user = salesUsers[i];
                    var cp = checkpoints[i];
                    var tgl = baseDate.AddDays(i);

                    if (!await db.SalesDailyTargets.AnyAsync(t => t.UserId == user.Id && t.TargetDate == tgl))
                    {
                        await db.SalesDailyTargets.AddAsync(new SalesDailyTarget
                        {
                            UserId = user.Id,
                            TargetDate = tgl,
                            TargetStores = 8 + (i % 4),
                            Notes = "Target kunjungan harian dummy",
                            CreatedBy = adminUser.Id,
                            CreatedAt = DateTime.UtcNow.AddDays(-10 + i)
                        });
                    }

                    if (!await db.AttendanceLogs.AnyAsync(a => a.UserId == user.Id && a.AttendanceDate == tgl))
                    {
                        var checkIn = DateTime.SpecifyKind(tgl.ToDateTime(new TimeOnly(8, 15)).AddMinutes(i), DateTimeKind.Utc);
                        var checkOut = DateTime.SpecifyKind(tgl.ToDateTime(new TimeOnly(17, 20)).AddMinutes(i), DateTimeKind.Utc);
                        await db.AttendanceLogs.AddAsync(new AttendanceLog
                        {
                            UserId = user.Id,
                            AttendanceDate = tgl,
                            CheckInAt = checkIn,
                            CheckOutAt = checkOut,
                            CheckInLatitude = cp.Latitude + 0.0012,
                            CheckInLongitude = cp.Longitude + 0.0011,
                            CheckOutLatitude = cp.Latitude + 0.0008,
                            CheckOutLongitude = cp.Longitude + 0.0007,
                            Status = i % 6 == 0 ? "late" : "present",
                            Notes = "Absen otomatis dummy",
                            CreatedAt = checkIn
                        });
                    }

                    var existingSubmission = await db.StoreSubmissions.FirstOrDefaultAsync(s =>
                        s.SalesUserId == user.Id &&
                        s.StoreName == cp.CheckpointName &&
                        s.ProposedVisitDate == tgl);

                    if (existingSubmission == null)
                    {
                        existingSubmission = new StoreSubmission
                        {
                            SalesUserId = user.Id,
                            StoreName = cp.CheckpointName,
                            Address = cp.Address,
                            Latitude = cp.Latitude,
                            Longitude = cp.Longitude,
                            RadiusMeters = cp.RadiusMeters,
                            SubmissionNote = "Pengajuan toko oleh sales (dummy)",
                            Status = "approved",
                            AdminNote = "Disetujui untuk kunjungan wajib",
                            ProposedVisitDate = tgl,
                            ApprovedCheckpointId = cp.Id,
                            ApprovedBy = adminUser.Id,
                            ApprovedAt = DateTime.UtcNow.AddDays(-9 + i),
                            CreatedAt = DateTime.UtcNow.AddDays(-10 + i)
                        };
                        await db.StoreSubmissions.AddAsync(existingSubmission);
                        await db.SaveChangesAsync();
                    }

                    if (!await db.SalesVisits.AnyAsync(v => v.UserId == user.Id && v.CheckpointId == cp.Id && v.VisitDate == tgl))
                    {
                        var arrived = DateTime.SpecifyKind(tgl.ToDateTime(new TimeOnly(10, 5)).AddMinutes(i * 4), DateTimeKind.Utc);
                        await db.SalesVisits.AddAsync(new SalesVisit
                        {
                            UserId = user.Id,
                            CheckpointId = cp.Id,
                            VisitDate = tgl,
                            Status = i % 5 == 0 ? "arrived" : "completed",
                            ArrivedAt = arrived,
                            LatitudeArrived = cp.Latitude + 0.0003,
                            LongitudeArrived = cp.Longitude + 0.0004,
                            Notes = "Kunjungan toko & update stok (dummy)",
                            VisitPhotoPath = $"/uploads/visit/dummy_visit_{i + 1:00}.jpg",
                            PointEarned = 70 + (i % 4) * 10,
                            IsMandatory = true,
                            SourceSubmissionId = existingSubmission.Id,
                            CreatedAt = arrived.AddMinutes(-15)
                        });
                    }

                    var dayStartUtc = DateTime.SpecifyKind(tgl.ToDateTime(TimeOnly.MinValue), DateTimeKind.Utc);
                    var dayEndUtc = dayStartUtc.AddDays(1);
                    var hasGpsForDate = await db.GpsLogs.AnyAsync(g =>
                        g.UserId == user.Id &&
                        g.LoggedAt >= dayStartUtc &&
                        g.LoggedAt < dayEndUtc);

                    if (!hasGpsForDate)
                    {
                        await db.GpsLogs.AddRangeAsync(
                            new GpsLog
                            {
                                UserId = user.Id,
                                Latitude = cp.Latitude - 0.0040,
                                Longitude = cp.Longitude - 0.0035,
                                Accuracy = 8.5,
                                LoggedAt = DateTime.SpecifyKind(tgl.ToDateTime(new TimeOnly(9, 30)), DateTimeKind.Utc)
                            },
                            new GpsLog
                            {
                                UserId = user.Id,
                                Latitude = cp.Latitude - 0.0015,
                                Longitude = cp.Longitude - 0.0010,
                                Accuracy = 6.0,
                                LoggedAt = DateTime.SpecifyKind(tgl.ToDateTime(new TimeOnly(9, 52)), DateTimeKind.Utc)
                            },
                            new GpsLog
                            {
                                UserId = user.Id,
                                Latitude = cp.Latitude + 0.0002,
                                Longitude = cp.Longitude + 0.0002,
                                Accuracy = 4.5,
                                LoggedAt = DateTime.SpecifyKind(tgl.ToDateTime(new TimeOnly(10, 6)), DateTimeKind.Utc)
                            });
                    }
                }

                // Dummy live movement: sales terlihat sedang perjalanan menuju toko (60 menit terakhir).
                var today = DateOnly.FromDateTime(DateTime.Today);
                var nowUtc = DateTime.UtcNow;
                for (int i = 0; i < 10; i++)
                {
                    var user = salesUsers[i];
                    var cp = checkpoints[i];

                    var todayVisit = await db.SalesVisits.FirstOrDefaultAsync(v =>
                        v.UserId == user.Id &&
                        v.CheckpointId == cp.Id &&
                        v.VisitDate == today);

                    if (todayVisit == null)
                    {
                        todayVisit = new SalesVisit
                        {
                            UserId = user.Id,
                            CheckpointId = cp.Id,
                            VisitDate = today,
                            Status = "pending",
                            Notes = "Rute kunjungan hari ini (dummy live)",
                            IsMandatory = true,
                            PointEarned = 0,
                            CreatedAt = nowUtc.AddHours(-2)
                        };
                        await db.SalesVisits.AddAsync(todayVisit);
                    }

                    var recentExists = await db.GpsLogs.AnyAsync(g =>
                        g.UserId == user.Id &&
                        g.LoggedAt >= nowUtc.AddMinutes(-70));

                    if (recentExists) continue;

                    // Start -> mid -> near checkpoint -> very near checkpoint.
                    var livePoints = new[]
                    {
                        new { Lat = cp.Latitude - 0.0200, Lng = cp.Longitude - 0.0180, MinAgo = 58, Acc = 12.0 },
                        new { Lat = cp.Latitude - 0.0110, Lng = cp.Longitude - 0.0090, MinAgo = 42, Acc = 9.0 },
                        new { Lat = cp.Latitude - 0.0055, Lng = cp.Longitude - 0.0042, MinAgo = 25, Acc = 7.0 },
                        new { Lat = cp.Latitude - 0.0017, Lng = cp.Longitude - 0.0013, MinAgo = 10, Acc = 5.0 },
                        new { Lat = cp.Latitude - 0.0006, Lng = cp.Longitude - 0.0004, MinAgo = 3,  Acc = 4.0 }
                    };

                    foreach (var p in livePoints)
                    {
                        await db.GpsLogs.AddAsync(new GpsLog
                        {
                            UserId = user.Id,
                            Latitude = p.Lat,
                            Longitude = p.Lng,
                            Accuracy = p.Acc,
                            LoggedAt = nowUtc.AddMinutes(-p.MinAgo)
                        });
                    }
                }

                if (!await db.AttendanceSettings.AnyAsync())
                {
                    await db.AttendanceSettings.AddAsync(new AttendanceSetting
                    {
                        LocationName = "Kantor Pusat NavSnap Makassar",
                        Latitude = -5.1476,
                        Longitude = 119.4327,
                        RadiusMeters = 150,
                        IsActive = true,
                        CreatedBy = adminUser.Id,
                        CreatedAt = DateTime.UtcNow
                    });
                }

                await db.SaveChangesAsync();

                var activeAttendance = await db.AttendanceSettings
                    .Where(x => x.IsActive)
                    .OrderByDescending(x => x.CreatedAt)
                    .FirstOrDefaultAsync();
                if (activeAttendance != null)
                {
                    var hasGeoPoints = await db.AttendanceGeofencePoints
                        .AnyAsync(x => x.AttendanceSettingId == activeAttendance.Id);
                    if (!hasGeoPoints)
                    {
                        var dLat = 0.0013;
                        var dLng = 0.0013;
                        await db.AttendanceGeofencePoints.AddRangeAsync(
                            new AttendanceGeofencePoint { AttendanceSettingId = activeAttendance.Id, SeqNo = 1, Latitude = activeAttendance.Latitude - dLat, Longitude = activeAttendance.Longitude - dLng },
                            new AttendanceGeofencePoint { AttendanceSettingId = activeAttendance.Id, SeqNo = 2, Latitude = activeAttendance.Latitude - dLat, Longitude = activeAttendance.Longitude + dLng },
                            new AttendanceGeofencePoint { AttendanceSettingId = activeAttendance.Id, SeqNo = 3, Latitude = activeAttendance.Latitude + dLat, Longitude = activeAttendance.Longitude + dLng },
                            new AttendanceGeofencePoint { AttendanceSettingId = activeAttendance.Id, SeqNo = 4, Latitude = activeAttendance.Latitude + dLat, Longitude = activeAttendance.Longitude - dLng }
                        );
                        await db.SaveChangesAsync();
                    }
                }
            }

            var seedAdmin = await db.Users.FirstOrDefaultAsync(u => u.Username == "admin");
            var seedSales = await db.UserRoles
                .Include(ur => ur.User)
                .Include(ur => ur.Role)
                .Where(ur => ur.Role.RoleName == "Sales")
                .Select(ur => ur.User)
                .OrderBy(u => u.FullName)
                .Take(5)
                .ToListAsync();
            var seedCheckpoints = await db.Checkpoints
                .Where(c => c.IsActive)
                .OrderBy(c => c.CheckpointName)
                .Take(5)
                .ToListAsync();

            if (seedSales.Any() && seedCheckpoints.Any() && !await db.SalesVisitReports.AnyAsync())
            {
                for (var i = 0; i < Math.Min(seedSales.Count, seedCheckpoints.Count); i++)
                {
                    await db.SalesVisitReports.AddAsync(new SalesVisitReport
                    {
                        UserId = seedSales[i].Id,
                        CheckpointId = seedCheckpoints[i].Id,
                        ReportDate = DateOnly.FromDateTime(DateTime.Today.AddDays(-i)),
                        VisitStatus = i % 3 == 0 ? "completed" : "arrived",
                        Outcome = i % 2 == 0 ? "Order follow-up minggu depan" : "Display produk diperbarui",
                        Notes = "Dummy report kunjungan sales"
                    });
                }
            }

            if (!await db.PayrollAutoSends.AnyAsync())
            {
                await db.PayrollAutoSends.AddRangeAsync(
                    new PayrollAutoSend { PayrollPeriod = "2026-05", SendDate = new DateOnly(2026, 5, 25), Status = "sent", RecipientCount = 48, SentAt = DateTime.UtcNow.AddDays(-8), Notes = "Slip gaji Mei terkirim otomatis" },
                    new PayrollAutoSend { PayrollPeriod = "2026-06", SendDate = new DateOnly(2026, 6, 25), Status = "scheduled", RecipientCount = 52, Notes = "Jadwal payroll bulan Juni" }
                );
            }

            if (seedSales.Any() && !await db.WorkArrangementRequests.AnyAsync())
            {
                await db.WorkArrangementRequests.AddRangeAsync(
                    new WorkArrangementRequest { UserId = seedSales[0].Id, ArrangementType = "WFH", WorkDateFrom = DateOnly.FromDateTime(DateTime.Today.AddDays(1)), WorkDateTo = DateOnly.FromDateTime(DateTime.Today.AddDays(1)), Location = "Rumah - Makassar", Reason = "Pekerjaan administrasi dan follow-up pelanggan", Status = "pending" },
                    new WorkArrangementRequest { UserId = seedSales[Math.Min(1, seedSales.Count - 1)].Id, ArrangementType = "WFA", WorkDateFrom = DateOnly.FromDateTime(DateTime.Today.AddDays(2)), WorkDateTo = DateOnly.FromDateTime(DateTime.Today.AddDays(3)), Location = "Area Gowa", Reason = "Kunjungan cluster luar kantor", Status = "approved", ApprovedBy = seedAdmin?.Id, ApprovedAt = DateTime.UtcNow.AddDays(-1) }
                );
            }

            if (seedSales.Any() && !await db.SalesTargetCompliances.AnyAsync())
            {
                for (var i = 0; i < seedSales.Count; i++)
                {
                    var target = 10 + i;
                    var actual = Math.Max(5, target - i - 1);
                    var percent = Math.Round((double)actual / target * 100, 1);
                    await db.SalesTargetCompliances.AddAsync(new SalesTargetCompliance
                    {
                        UserId = seedSales[i].Id,
                        ComplianceDate = DateOnly.FromDateTime(DateTime.Today.AddDays(-i)),
                        TargetVisits = target,
                        ActualVisits = actual,
                        CompliancePercent = percent,
                        Status = percent >= 90 ? "compliant" : percent >= 75 ? "watch" : "risk",
                        Notes = "Dummy compliance sales target"
                    });
                }
            }

            if (!await db.RecruitmentCandidates.AnyAsync())
            {
                await db.RecruitmentCandidates.AddRangeAsync(
                    new RecruitmentCandidate { CandidateName = "Rahma Putri", Email = "rahma.putri@example.com", Phone = "08123450001", PositionApplied = "Sales Executive", Stage = "Interview User", Status = "active", Source = "LinkedIn" },
                    new RecruitmentCandidate { CandidateName = "Ardi Nugroho", Email = "ardi.nugroho@example.com", Phone = "08123450002", PositionApplied = "Area Sales", Stage = "Offering", Status = "active", Source = "Referral" },
                    new RecruitmentCandidate { CandidateName = "Maya Lestari", Email = "maya.lestari@example.com", Phone = "08123450003", PositionApplied = "HR Officer", Stage = "Screening", Status = "active", Source = "Job Portal" }
                );
                await db.SaveChangesAsync();
            }

            var candidates = await db.RecruitmentCandidates.OrderBy(c => c.Id).Take(3).ToListAsync();
            if (candidates.Any() && !await db.OnboardingTasks.AnyAsync())
            {
                foreach (var candidate in candidates)
                {
                    await db.OnboardingTasks.AddAsync(new OnboardingTask
                    {
                        CandidateId = candidate.Id,
                        EmployeeName = candidate.CandidateName,
                        TaskName = "Lengkapi dokumen karyawan",
                        DueDate = DateOnly.FromDateTime(DateTime.Today.AddDays(7)),
                        Status = "open",
                        OwnerName = "HR Operations",
                        Notes = "Dummy onboarding task"
                    });
                }
            }

            if (candidates.Any() && !await db.CvMasterSummaries.AnyAsync())
            {
                foreach (var candidate in candidates)
                {
                    await db.CvMasterSummaries.AddAsync(new CvMasterSummary
                    {
                        CandidateId = candidate.Id,
                        CandidateName = candidate.CandidateName,
                        Position = candidate.PositionApplied,
                        LastEducation = "S1 Manajemen",
                        YearsExperience = candidate.Id % 4 + 1,
                        Skills = "Sales operation, reporting, customer visit",
                        Summary = "Kandidat dummy dengan pengalaman relevan untuk kebutuhan NavSnap.",
                        Score = 78 + candidate.Id % 12
                    });
                }
            }

            await db.SaveChangesAsync();
        }
    }
}
